# Generated by Django 3.2.16 on 2025-01-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20250110_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherinfo',
            name='city_name',
            field=models.CharField(max_length=100),
        ),
    ]
