# Generated by Django 3.2.16 on 2025-01-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_weatherinfo_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherinfo',
            name='imperial',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
